name: Cleanup PR Images

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - name: evis_ocpp_emulator-backend
          - name: evis_ocpp_emulator-ui

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: ${{ matrix.name }}
          delete-tags: ${{ github.event.pull_request.head.ref }}
